### PR TITLE
skip interpolating escaped strings, closes #33

### LINKED ISSUE #33: Skip interpolation of escaped strings
Strings like `\${config.varname}` are currently treated as config variables. These should be skipped and interpolated into `${config.varname}`

### PR DESCRIPTION
**Pull request by kg6zvp**
- code cleanup
- added test case for escaped vars

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Thoughts on this @jmesnil, @mkouba?

**Comment by mkouba** [comment]
If I understand it correctly `StringInterpolator` is just a util class, not used anywhere in `smallrye-config
` codebase?

**Comment by kenfinnigan** [comment]
That's my understanding yes

**Comment by mkouba** [comment]
Well, I'm not a fan of exposing generic util classes like this but since it's already there we should at least add some javadoc, make the class final and add a private constructor ;-)

**Comment by bobmcwhirter** [comment]
I think I intended (if I even wrote the code? I did for Thorntail) for it to be purely internal, not a public utility.  Who knows.  It's friday.

**Comment by kg6zvp** [comment]
I'll take the blame for adding this. I submitted a PR with this yesterday, I think, with the intention of integrating it's use into Thorntail. As stated on PR 36, I'm happy to refactor this into a separate utility for integration with Thorntail.

**Comment by kg6zvp** [comment]
Will be integrated into Thorntail otherwise

**Pull request closed without merging**
