### PR TITLE
Fix Converter Priority and add unit test

### PR DESCRIPTION
**Pull request by tevans78**
Signed-off-by: tevans <tevans@uk.ibm.com>

@radcortez The `SmallRyeConfigBuilder.addConverter` method always stored the annotated priority rather than the one provided as a parameter.

### CODE REVIEW

**Comment by radcortez** [comment]
@tevans78 Thanks!

Can you please, provide this PR to `master` and then we can rebase it with the `2.0` branch. Is just that this is a general bug and not related with `2.0` implementation, so we can benefit to have it in master. We don't really know when are we going to be able to release `2.0`.

**Comment by tevans78** [comment]
@radcortez I will create a PR for master but please can you rebase the 2.0 branch as soon as it has been merged?

**Comment by radcortez** [comment]
Of course :)

**Comment by radcortez** [comment]
Rebased. Closing this PR. Thanks!

**Pull request closed without merging**
