### PR TITLE
Don't directly search WEB-INF/classes for config properties files

### LINKED ISSUE #522: Duplicate microprofile-config.properties ConfigSoucres from Config.getConfigSources()
For example:
```
Config config = ConfigProvider.getConfig();
System.out.println("Default ConfigSources: "+config.getConfigSources());
```

Produces (split across new lines for readability):
```
Default ConfigSources: [
SysPropConfigSource, 
EnvConfigSource, 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
DefaultValuesConfigSource
]
```

These 2 microprofile-config.properties ConfigSources contain the same properties (from `.getProperties()`) but are not equal (from `.equals()`)  

The same thing also happens for `microprofile-config-<profile_name>.properties` for Config Profiles on the [Config Source level](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_on_config_source_level).

### PR DESCRIPTION
**Pull request by tevans78**
fixes #522

### CODE REVIEW

**Comment by tevans78** [comment]
@radcortez I included your new test. Are there any others you think should be added? I was slightly surprised that I didn't have to change anything else.

**Comment by radcortez** [comment]
Thanks, I think the change should be fine. To be on the safe side, we can add an additional test that adds the config file as `.addAsWebInfResource(mpConfig, "classes/META-INF/microprofile-config.properties");` into the Arquillian archive. And this one should also be loaded.

**Comment by radcortez** [comment]
I think it doesn't make any difference. I've tried it myself and Arquillian will always create the file in the same place.

**Comment by radcortez** [comment]
@kabir do you see any issue from the Wildfly side? I've tried this with the config quickstart and it seems to work. There may be some other uses cases that I'm not aware.

**Comment by kabir** [comment]
@radcortez I'll  run some parts of our testsuite locally to see what happens (assuming/checking that SM Config master works with WildFly first before testing this change)

**Comment by radcortez** [comment]
Thanks!

**Comment by kabir** [comment]
Thank you for thinking of us :)

I've run everything I can think of and it all seems to work fine with this fix. If I missed something and end up needing this again, I guess I can provide my own SmallRyeConfigProviderResolver or something and add this back into a builder. But I don't think that is very likely.

**Comment by radcortez** [comment]
Thanks, I'll merge this. If if you find any issue let me know and we figure something else.

**Review by radcortez — APPROVED** [review]

**Pull request merged**
