### PR TITLE
Support for Supplier<T> in @ConfigMapping Interfaces

### LINKED ISSUE #664: Support Provider<T> within @ConfigMapping Class
Reference docs: https://smallrye.io/docs/smallrye-config/mapping/mapping.html

It would be nice to support injection of `javax.inject.Provider<T>` into a class anotated with `@ConfigMapping` such that the value can be potentially evaluated dynamically at runtime.

Example:

```java
import javax.inject.Provider;

@ConfigMapping(prefix = "server")
interface Server {
    Provider<String> host();

    int port();
}
```

`javax.inject.Provider` injection is already supported for `@ConffigProperty` by microprofile config as outlined in JavaDocs here:
https://download.eclipse.org/microprofile/microprofile-2.0-javadocs-test/apidocs/org/eclipse/microprofile/config/inject/ConfigProperty.html

### PR DESCRIPTION
**Pull request by brianwyka**
Closes #664

### CODE REVIEW

**Review by radcortez — CHANGES_REQUESTED** [review]
Thanks @brianwyka.

Can you please rebase and run the build to apply the proper formatting?

How about the TODO in the ASM implementation?

**Comment by brianwyka** [comment]
Will do @radcortez.  As for the `TODO` in ASM, I will most likely need some help there to complete.

**Comment by radcortez** [comment]
> Will do @radcortez. As for the `TODO` in ASM, I will most likely need some help there to complete.

My recommendation is to just grab one Java to ASM plugin (IntelliJ has a few). I guess other IDEs should have them as well. Write the java code you need and see the corresponding ASM and copy it to the Generator class (of course it may need adjustments).

**Comment by radcortez** [comment]
This PR has been stalled for a few months. Closing this for now. Please reopen it if you want to keep working on it. Thank you!

**Pull request closed without merging**
