### PR TITLE
Add ConfigSource for TOML format.

### PR DESCRIPTION
**Pull request by radcortez**
Prototype to support the `TOML` format.

- [x] This requires https://github.com/smallrye/smallrye-config/pull/489 to support Collections mappings.
- No support for bidimensional collections.
- The library used to parse the file, does the conversion, but we need the values as Strings because Config expects String and has its own Conversion mechanism.

### CODE REVIEW

**Comment by geoand** [comment]
👍

**Comment by mschorsch** [comment]
Is there any progress on this issue? I'm waiting eagerly 😃

**Comment by radcortez** [comment]
> Is there any progress on this issue? I'm waiting eagerly 😃

We didn't see interest in it, so no further work was done here. Are you looking to use this in Quarkus?

**Comment by mschorsch** [comment]
> > Is there any progress on this issue? I'm waiting eagerly 😃
> 
> We didn't see interest in it, so no further work was done here. Are you looking to use this in Quarkus?

Yes 😁

**Comment by radcortez** [comment]
I am closing this due to the lack of interest.

**Comment by maxandersen** [comment]
count me as interested :)

**Comment by radcortez** [comment]
If you need it, we can definitely revisit this. Where are you looking to use it?

**Comment by maxandersen** [comment]
@radcortez its was while looking for how/what to use for configuration for jhostty. was looking at apple pkl due to its amends feature and programmatic DSL generator - but 9 mb + truffle dependency wasn't great - so I wanted to try smallrye config and had hoped could use toml or other language that is less "pedantic" or "verbose" compared to properties/json/yaml.

**Pull request closed without merging**
