### PR TITLE
Change getConverter to match proposed MP Config 2.0 API without breaking compatibility

### PR DESCRIPTION
**Pull request by dmlloyd**
Depends on eclipse/microprofile-config#495; don't take out of draft until/unless that gets merged.

### CODE REVIEW

**Comment by radcortez** [comment]
Not only we need the merge in MP Config, but also the release of the new artifact. 

What do you think if we create a MP 2.0 branch for breaking changes dependant on the MP Config API binaries?

**Comment by dmlloyd** [comment]
We don't need the release of the new (MP Config 2.0) artifact (unless we want to add the `@Override` annotation which I do not view as important) in order to merge this change; it's binary compatible with both the old and new APIs AFAICT.

**Comment by radcortez** [comment]
Ok!

**Comment by radcortez** [comment]
Merged in branch `mpconfig20`.

**Pull request closed without merging**
