### PR TITLE
Add test to check default ConfigSources.

### LINKED ISSUE #522: Duplicate microprofile-config.properties ConfigSoucres from Config.getConfigSources()
For example:
```
Config config = ConfigProvider.getConfig();
System.out.println("Default ConfigSources: "+config.getConfigSources());
```

Produces (split across new lines for readability):
```
Default ConfigSources: [
SysPropConfigSource, 
EnvConfigSource, 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
DefaultValuesConfigSource
]
```

These 2 microprofile-config.properties ConfigSources contain the same properties (from `.getProperties()`) but are not equal (from `.equals()`)  

The same thing also happens for `microprofile-config-<profile_name>.properties` for Config Profiles on the [Config Source level](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_on_config_source_level).

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #522

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
Could you try using `.addAsWebInfResource(` instead of `.addAsResource(` please?

**Comment by radcortez** [comment]
So actually I did some tests and they work in the same way. Both place the file in `/WEB-INF/classes/META-INF/microprofile-config.properties`.

**Comment by radcortez** [comment]
It seems that the duplicated resources might be coming from the dual check in the builder. In theory `WEB-INF/classes/META-INF/microprofile-config.properties` shouldn't be loading anything, since a web classloader places all resources from `/classes` and the valid path it `META-INF/microprofile-config.properties`.

How is the layout of the application you are seeing this behaviour?

**Comment by Joseph-Cass** [comment]
> How is the layout of the application you are seeing this behaviour?

Tom discusses this here: https://github.com/smallrye/smallrye-config/issues/522#issuecomment-800468798

**Comment by radcortez** [comment]
Moved to https://github.com/smallrye/smallrye-config/pull/528.

**Pull request closed without merging**
