### PR TITLE
[#60] Support for non-object Optional* types

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is one possible approach for how `Optional*` could be implemented.  An advantage of this approach is that the existing converters infrastructure is reused.  A disadvantage is that it gets a little weird in that you can have arrays/lists of `Optional*`s which might or might not be an anti-pattern of sorts.

**Comment by jmesnil** [comment]
@dmlloyd thanks, that is a good enhancement.

I took the liberty to take your PR and update it to put the support of these optional types into the `Config#getValue` method (there is no reason these types could not be supported from the Config API directly)
I've also added tests to check the behaviour.

If that's ok with you, I'll close this PR and merge #62 that contains your code + mine.

**Comment by dmlloyd** [comment]
That's fine, thanks. As long as you think that the approach is okay that is.

**Comment by jmesnil** [comment]
superseded by #62

**Pull request closed without merging**
