### PR TITLE
Fixed issue with property names and member names in ConfigMappings.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by hrstoyanov** [comment]
@radcortez which maven artifact should I use to pull this fix?

**Comment by radcortez** [comment]
Didn't release this yet. I still need to backport it to `1.x`. I'll let you know when its done.

**Comment by radcortez** [comment]
Created Backports: 
- #575 to [backport-570-to-1.x](https://github.com/smallrye/smallrye-config/tree/1.x)

**Comment by hrstoyanov** [comment]
@radcortez thank you!

**Pull request merged**
