### PR TITLE
Empty values are always treated as non-present

### LINKED ISSUE #83: Inconsistent behaviour between `Config.getValue()` and `Config.getOptionalValue()`
I stumbled upon the different behaviour of `Config.getValue()` and `Config.getOptionalValue()` method.

When you define a configuration and give it an empty value, e.g. something like `org.foo.bar=` (expected value here is `String[]`, then `getValue()` will (IMO correctly) return empty string, whereas `getOptionalValue()` gives me empty optional which I cannot retrieve.

Now, I don't really see spec mentioning this in detail, but those two methods should behave equally.

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #83 (for real)

### CODE REVIEW

**Comment by dmlloyd** [comment]
This is a draft PR because it does not pass TCK due to https://github.com/eclipse/microprofile-config/pull/407

**Comment by kenfinnigan** [comment]
Depending on what happens with the spec, we can "exclude" the failing test(s) so the build passes if we need it released.

It's safe to exclude on the premise we're challenging the TCK

**Comment by dmlloyd** [comment]
OK I've disabled the offending TCK tests.

**Comment by jmesnil** [comment]
Let's merge this and discuss the spec behaviour in https://github.com/eclipse/microprofile-config/pull/407

**Comment by kenfinnigan** [comment]
Do we need another release?

**Comment by dmlloyd** [comment]
Yes please

**Pull request merged**
