### PR TITLE
Match the correct overridden method in a mapping hierarchy

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by nastra** [comment]
@radcortez do you know when 2.4.3 will be released?

**Comment by radcortez** [comment]
I can probably do it today.

**Comment by nastra** [comment]
do you think https://github.com/quarkusio/quarkus/pull/18497 will make it into the release as well?

**Comment by radcortez** [comment]
No, that one is probably going to take a while. While it is ready it introduces a lot of changes, and Quarkus 2.2 is going to be a hardening release, so no risky changes. Sorry for the inconvenience :(

**Comment by radcortez** [comment]
@nastra Just released SR Config 2.4.3. You should be able to manually update it with the latest Quarkus version to get the fix.

**Pull request merged**
