### PR TITLE
[#66] Add ability to wrap configuration sources (with tests)

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by jmesnil** [comment]
@dmlloyd Is that "prototype" implementation or "final" implementation? ;)

In both cases, looks good to me :)

**Comment by dmlloyd** [comment]
I am happy with this approach; it can be "final" if you like it!

**Comment by jmesnil** [comment]
@dmlloyd could you please rebase? the merge of #67 has created a conflict with this one.

**Comment by dmlloyd** [comment]
Rebased.

**Comment by jmesnil** [comment]
thanks!

**Pull request merged**
